name: chatXpress
description: A cross-platform Flutter project with chatGPT API.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.3
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  google_sign_in: ^6.1.4
  chat_gpt_sdk: 2.2.4
  envied: ^0.3.0+3
  sign_in_with_apple: ^5.0.0
  cloud_firestore: ^4.8.4
  get_it: ^7.6.0
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.18.1
  flutter_lints: ^2.0.0
  envied_generator: ^0.3.0+3
  build_runner: ^2.4.6

flutter:
  uses-material-design: true


  fonts:
    - family: IndieFlower
      fonts:
        - asset: fonts/IndieFlower-Regular.ttf
    - family: Mulish
      fonts:
        - asset: fonts/Mulish-VariableFont_wght.ttf


  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  macos:
    generate: true
    image_path: "assets/icons/ios/chatXpress_ios_icon.png"
  image_path: "assets/icons/ios/chatXpress_ios_icon.png"
  adaptive_icon_background: "#00A67E"
  adaptive_icon_foreground: "assets/icons/android/chatXpress_android_foreground.png"
