// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6zEfuviPzmLRFaToZQN-Z55Ti5Y-hAgs',
    appId: '1:183583835985:web:a4a96f3b61c6a2f4a6f570',
    messagingSenderId: '183583835985',
    projectId: 'chatxpress',
    authDomain: 'chatxpress-c4b32.firebaseapp.com',
    storageBucket: 'chatxpress.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRKSLRmzB6M9IJqQVlWZCla-YTRxSlPUc',
    appId: '1:183583835985:android:9d0e735eb225aa50a6f570',
    messagingSenderId: '183583835985',
    projectId: 'chatxpress',
    storageBucket: 'chatxpress.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABUO_h0cRugu2KUnSqHpnZWAb_HfAoZQk',
    appId: '1:183583835985:ios:b585c79cc2aebe10a6f570',
    messagingSenderId: '183583835985',
    projectId: 'chatxpress',
    storageBucket: 'chatxpress.appspot.com',
    iosClientId: '183583835985-rddfjl7d51q7jjpbbtd3ffet10f5rqih.apps.googleusercontent.com',
    iosBundleId: 'com.chatxpress.chatxpress',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABUO_h0cRugu2KUnSqHpnZWAb_HfAoZQk',
    appId: '1:183583835985:ios:d50eef90e99b5946a6f570',
    messagingSenderId: '183583835985',
    projectId: 'chatxpress',
    storageBucket: 'chatxpress.appspot.com',
    iosClientId: '183583835985-vc6p2s238fds1vf7t2s1ecn3nfek1qkt.apps.googleusercontent.com',
    iosBundleId: 'com.chatxpress.chatxpress.RunnerTests',
  );
}
